### ISSUE TITLE
s3 access problem using compose

### ISSUE THREAD

**Issue by lsfera** [localstack/terraform-local#26]
With the following configuration:
```
#docker-compose.yml
version: "3.8"

services:
    localstack:
  #canonical configuration - https://github.com/localstack/localstack/blob/master/docker-compose.yml
  [...]
    setup-infrastructure:
      volumes:
          - ./terraform:/usr/infrastructure
       working_dir: /usr/infrastructure
       command:
           - /bin/sh
           - -c
           - |
             tslocal init #-upgrade
             tslocal workspace select -or-create localstack
             terraform apply -auto-approve -lock=false
```

the only way to ensure that S3 works properly is by setting  `s3_use_path_style=true` and all endpoints to `http://localstack:4566`  as following:
```
#./terraform/main.ts 
provider "aws" {
    region = "eu-west-1"
    access_key = "anaccesskey"
    secret_key = "asecretkey"
    skip_credentials_validation = true
    skip_requesting_account_id = true 
    skip_metadata_api_check = true
    s3_use_path_style = true
    
    endpoints {
        s3  = "http://localstack:4566"
  }
}

resource "random_string" "id" {
  length    =   "5"
  special   =   false
  upper     =   false
}

resource "aws_s3_bucket" "bucket" {
  bucket    =   "mybucket-s3-g2-${random_string.id.result}"
}
```

This combination does not seem achievable through tflocal, probably due to https://github.com/localstack/terraform-local/blob/main/bin/tflocal#L214C9-L217

I'm working with WSL2(Win OS), btw.

https://github.com/lsfera/localstack-testing for a quick review
